### ISSUE TITLE
"Edit Work Order" page hangs on loading

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobile-signals-work-orders#104]
<img width="1552" alt="Screen Shot 2019-06-13 at 8 36 57 AM" src="https://user-images.githubusercontent.com/1463708/59437451-3fc64200-8db7-11e9-9532-6bf652bcb1ce.png">

**Comment by mateoclarke** [comment]
Thanks for opening this one @amenity.

### Steps to reproduce
- Login as roman.pena
- Go to a work order page
- Click Edit
Here's a direct url: https://react-knack.netlify.com/work-order/edit/5c5c8d6bffdb0f62c750f1c5

**Comment by mddilley** [comment]
Noticed issue with Lead Technicians not saving, possibly related to knack-data-tracker number 20
