### ISSUE TITLE
7/31 Mobile Signals MVP Sprint Review

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobile-signals-work-orders#144]
### Agenda

- Discuss usability findings
- Demo camera functionality
- Launch plan
- Prioritize next features/enhancements
------
- [x] Schedule meeting
- [x] Meet
- [x] Attach meeting notes to this issue
- [ ] Create resulting issues

**Comment by mddilley** [comment]
Just saw this - I think that is a great idea, @amenity! This is a great way to keep momentum going forward when facing style decisions.

**Comment by johnclary** [comment]
updated link to the [knack style guide](https://atd-dts.gitbook.io/atd-knack-operations/knack/style-guide)
