### ISSUE TITLE
field_211 (WORK_LOCATION) does not update when editing Signal field of a Work Order

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-mobile-signals-work-orders#158]
@dianamartin I found this issue when updating the field_ids and testing the New and Edit Work Order forms in the React app.

Steps to reproduce in Knack app:
1. Create a New Work Order with Signal Asset Type (https://atd.knack.com/13-aug-2019--test-austin-transportation-data-tracker#my-work-orders/new-work-order/)

**Work Order Details view with Work Location (field_211) matching Signal ID after creating**
<img width="576" alt="Screen Shot 2019-08-16 at 1 39 40 PM" src="https://user-images.githubusercontent.com/37249039/63190446-d4eded00-c02b-11e9-992b-688e4d51431f.png">

2. Edit Signal field in Edit Work Order Mobile view
3. Work Order Heading (field_211) doesn’t update with correct Work Location after submitting edit form.

**Work Order Details view with Work Location (field_211) not matching Signal ID after updating**
<img width="576" alt="Screen Shot 2019-08-16 at 1 40 11 PM" src="https://user-images.githubusercontent.com/37249039/63190510-f5b64280-c02b-11e9-87ae-a0335add07bd.png">

In the old TEST (7 FEB 2019 | TEST - ATD Data Tracker), field_211 updates correctly with the Old Edit Work Order Form (view_1082) but not with the New Edit Work Order Form (view_2474).

**Comment by dianamartin** [comment]
@mddilley I looked that that ticket you created in the Test environment and saw it was 100 instead of 10. I edited the record with the new work order mobile edit form and changed it to Signal ID: 10. 

Also, I created a new work order from the My Work Orders page, using the new mobile form. I selected Signal ID: 91, and it's the one I usually test. When it updated it showed up as Signal ID: 91. So I wasn't able to reproduce your error. I'll try the one you did too.

**Comment by mddilley** [comment]
@dianamartin Thanks for looking at this. I can show you what I am seeing on Monday. I'm not even sure how often anyone would update the Signal on a Work Order after creating it (maybe if they chose the wrong signal in the first place?).

**Comment by dianamartin** [comment]
@mddilley So, I created another work order for Signal ID: 10. It came up as Signal ID 10, i edited using the mobile form, added something to the description, didn't change the Signal ID. After submission, I still had Signal ID: 10. I'm not sure what happened when you were testing. Yeah, we can look at it on Monday too.

**Comment by dianamartin** [comment]
Work Order Details - `locations > LOCATION_NAME` 

Figure out relationship to Edit form

**Comment by johnclary** [comment]
@dianamartin would you follow up with Mike on this?

**Comment by dianamartin** [comment]
Followed up with Mike. Need to add Record Rules to Edit Signals Mobile form, looks like there are some missing.

**Comment by dianamartin** [comment]
I checked Production, the edit signal mobile form had the rules, but the test environment didn't have it. I configured the Test environment so they can test properly.
