### ISSUE TITLE
Find source of and test change in My Work Orders Knack url

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-mobile-signals-work-orders#167]
While add features to hide/show Work Order Details submit, re-open, and edit buttons, it was noticed that the Knack url for My Work Orders changed from https://atd.knack.com/13-aug-2019--test-austin-transportation-data-tracker#my-work-orders/my-work-order-details/ to https://atd.knack.com/13-aug-2019--test-austin-transportation-data-tracker#my-work-orders/my-work-order-details2/. The code for the API call was updated (see diff below).

Need to test if this change affects other parts of the app.

![Screen Shot 2019-08-27 at 11 33 49 AM](https://user-images.githubusercontent.com/37249039/63790356-b5be4d80-c8be-11e9-8cb1-2bb82708686c.png)

**Comment by amenity** [comment]
@mddilley - have you been working on this? If so, can you add estimate and assign yourself?

And should we open a new issue for the fix itself?

**Comment by mddilley** [comment]
@amenity - thanks for reminding me about this one. I fixed this issue in https://github.com/cityofaustin/atd-mobile-signals-work-orders/pull/172. This issue also does not affect any other parts of the app so I'll close this issue.
