### ISSUE TITLE
Mobile Signal Work Order | TESTING

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-mobile-signals-work-orders#168]
## Comments 
**CREATE WORK ORDER FORM**
- [ ] I didn't see a way to self assign without adding the support technician.

**WORK ORDER PAGE**
- [ ] On All Work Order page, there isn't a unique ID like the ATD WORK ORDER ID on the table, so you can't differentiate between the work sites other than time. 

**PHOTO** 
- [ ] While taking a photo, the user has to scroll down to see the "submit" button. It was not intuitive during testing, until we found the button.

**Comment by amenity** [comment]
@SurbhiBakshi @dianamartin - it looks like this is in progress? Can you add an estimate to it? 

Thanks!

**Comment by dianamartin** [comment]
We did testing before we did the pilot kick off to make sure there wasn't any issues with the mobile signal work orders that the Dev group needed to fix ahead of time.
