### ISSUE TITLE
Meet w/ Tech's Review Pilot 

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-mobile-signals-work-orders#181]
Scheduled for 9/11 @ 1pm - Bullick Hollow

**Comment by dianamartin** [comment]
Gene P. 
AMD 

Came by to let us know some mobile signals UI feedback

### Search for the signal
Not finding a signal (When creating a work order)
Gene said, he assumed that the signal would populate in the field like it does in the Fulcrum app. We went through it an he realized he can see the nearby signals (the marker pin shows up).

### Time Log
When entering a time log you can't choose 12 pm. It goes from 11:45 am to 12 am, not 12 pm. (ordering isn't correct). 
>We all tested on a tablet I had, it's incorrect. The library is incorrect according to Mateo.
- [x] Mateo created issue for this

### Editing Time Log
Unable to Edit Time Log currently, only able to add a new time log. Checked on the Test Environment of Data Tracker that techs had the ability to inline edit. Mateo said he'd build out an edit form for that page.
- [x] Mateo created issue for this

**Comment by SurbhiBakshi** [comment]
staff wants clarity on Home button
- interface needs to be optimized for cell phone

**Comment by dianamartin** [comment]
Notes from 9/11:
 
### Having refreshing or buffering lag
- just constantly spinning 

 ### Decision on: Detection buttons
**Detectors buttons available in main Search Signals page – Yes, need to add this button **
- Edit Detection form work orders (already has detector buttons)

**Comment by mddilley** [comment]
### Notes from 9/11/19 Pilot Feedback Meeting
**Dev Team**
- [ ] Need to be able to edit detectors in Search Signals view (outside of/prior to being associated with a work order, task can involve pulling up the signal itself and going through a checklist to edit the detectors)

- #186 Tablet unresponsive when trying to enable camera (won’t let user tap on “Allow” or “Deny” for camera permissions)

- [ ] HTML coming through in Work Specifications: Problem Found text field in Work Order Details view (Adding slashes is part of the user’s text entry for northbound, southbound, etc., 8th & Brazos record is an example)

- #187 On Asset Details, add File Attachments to view (for pdf drawings and other attachments) Tablets have Microsoft Excel to open .xlsx. Other file types are images or pdfs

**Apps Team**
- [ ] Make home screen icon shortcut on tablet (like Signs & Markings app)

**Comment by mddilley** [comment]
### Notes from 9/18/19

Toby reports that:
- Nearby Locations are not working. Shows `Loading…` and then never populates the list.
- When he tapped View Signal Details (from the Work Order Details view), nothing loaded and he saw a blank page
- When he tried to take a photo, the image captured does not render properly (see his screenshot below)
![photo-broken.jpg](https://images.zenhubusercontent.com/5cfe7d078509cb6dcbaafdc3/d5a10c15-3df0-4ab4-a3e8-440710292ab9)
