### ISSUE TITLE
Time options skip 12:00PM

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#183]
On the New Time Log page, there is no 12:00pm option. The values in the dropdown skip from 11:45am to 12:00pm to 12:15pm. It appears to just be mislabeled in the dropdown because once you select 12:00AM and the dropdown closes, the value in the input actually is 12:00PM.

This seems like it could be a bug in the time select library we're using. Might need to fork the library and fix their code, or select a different time select library. 

![Screen Shot 2019-09-10 at 9 41 45 AM](https://user-images.githubusercontent.com/5697474/64624044-a73c5f80-d3af-11e9-97b3-d8212c92054b.png)

![Sep-10-2019 09-44-37](https://user-images.githubusercontent.com/5697474/64624080-b4f1e500-d3af-11e9-837d-b0123de9aad2.gif)

**Comment by mddilley** [comment]
@mateoclarke @dianamartin I took a look at this issue, and I can't get the AM/PM to stack below the times in the dropdown. They are always side by side like this screenshot.

![Screen Shot 2019-09-10 at 3.21.56 PM.png](https://images.zenhubusercontent.com/5cfe7d078509cb6dcbaafdc3/d874f67e-d01d-45b1-a5a4-8f239be401ba)
I think what is happening is that the AM/PM part is dropping below the time and getting highlighted with the option below it (making it look like it is part of the option being selected even though it isn't). I'm using Chrome dev tools set to iPad and I even tried much smaller devices, and it still looks like my screenshot. Any tips on settings?

**Comment by dianamartin** [comment]
@mddilley I don't think the AM/PM side by side look bad, does it look bad on a tablet?
