### ISSUE TITLE
Configure Airwatch to let users to "Allow" Chrome browser to use current location and allow camera use

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#186]
https://docs.vmware.com/en/VMware-AirWatch/9.3/vmware-airwatch-guides-93/GUID-AW93-AFWProfile_Chrome_Brswr_Settings.html

**Comment by dianamartin** [comment]
I reached out to Danny Cullum from CTM. He's going to be walking me through the AirWatch Admin console. He said that "_there are no console setting to enforce browser settings_". Hopefully, I can learn how to set up a shortcut an a profile.

**Comment by dianamartin** [comment]
Was doing a bunch of testing on the tablets, I think that being in admin mode allows the user to click these alerts and accept the location tracking.

**Comment by dianamartin** [comment]
With all the testing, I think the work around for this is being in admin mode to accept the location prompt.
