### ISSUE TITLE
User permissions in PROD Data Tracker prevent Mobile Edit Form from being viewed

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-mobile-signals-work-orders#192]
In the production environment, user permissions for Test Technician prevent access to the "Edit Work Order | Mobile" view in the Knack app. In the React app, this prevents the Edit Work Order view from rendering and the Support Technicians dropdown in the New Work Order View from populating. When tested in the test environment (13 AUG 2019 | TEST - Austin Transportation Data Tracker), permissions allow access to this page as Test Technician (the only difference in permissions is the Mobile Pilot user role in PROD).

### User Roles
<img width="471" alt="Screen Shot 2019-09-13 at 9 40 32 AM" src="https://user-images.githubusercontent.com/37249039/64872227-6db46000-d60c-11e9-9d9b-e35c30559ba6.png">

### Knack app
<img width="871" alt="Screen Shot 2019-09-13 at 9 45 39 AM" src="https://user-images.githubusercontent.com/37249039/64872304-8fade280-d60c-11e9-929d-71e0f1770d9f.png">

### React app errors
<img width="1547" alt="Screen Shot 2019-09-13 at 9 21 29 AM" src="https://user-images.githubusercontent.com/37249039/64872339-a3594900-d60c-11e9-8731-fbd249ebf91c.png">

<img width="1547" alt="Screen Shot 2019-09-13 at 9 20 29 AM" src="https://user-images.githubusercontent.com/37249039/64872355-aa805700-d60c-11e9-83c3-1176be4ba3a3.png">

**Comment by dianamartin** [comment]
I added the `mobile pilot` user roles to this "Edit Signals Form | Mobile" and Mike said it seemed to fix it.

**Comment by mddilley** [comment]
Spoke with @dianamartin, and she resolved this by updating permissions for the "Edit Work Order | Mobile" view in Knack (Austin Transportation Data Tracker | PRODUCTION). Closing.

**API values below for React app**
```
sceneId: "scene_1048",
viewId: "view_2632",
```
