### ISSUE TITLE
Test Nearby Signals feature of the New Work Order form with technician-configured tablet

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-mobile-signals-work-orders#195]
The technicians participating in the pilot testing for the Mobile Signals Work Orders app have reported issues with nearby signals populating in the New Work Order form with their Airwatch-configured tablets.

Need to test the app with the same device and settings as a technician would in production. This can include comparing the locations auto-populating in the React mobile app and Fulcrum.

**Comment by dianamartin** [comment]
### Notes from testing on 9/13

I was able to do some testing on the tablet. I went to some food places to pick up something which were very close by to signal intersections. I was toggling between Chrome, Mobile Signals "short cut app" and Fulcrum. 

I was doing a lot of refreshing and I think there is a definite lag using the mobile signal work orders. 
It's takes about 5-10 min for it to "know" where you are. 

I opened Fulcrum up and it picked it up almost immediately.  I moved to another food location and got a drink and tested some more, same experience. It took several times of refreshing until it picked up the correct signal. 

Fulcrum had no problem finding the nearby signal though and it populates it in the field too. We definitely need to ask John if it will be possible to use the same code has for fulcrum app to the mobile signals "app".

**Comment by mddilley** [comment]
### Testing on 9/17
I tested this feature at Berkman/Briarcliff, Cameron/Briarcliff, Cameron/290, and Cameron/183. I noticed that the signals did not immediately populate in the React mobile app. In Fulcrum, the nearby signal would populate on the first attempt. I did notice that nearby signals would populate immediately in the React app **only after** opening Fulcrum and using the same feature in Fulcrum. 

- [ ] Need to find out why the device is not updating the user's location as readily in the React app and why updating the user's location in Fulcrum helps this feature out in the React app.
- [ ] Need to look into the Airwatch profile of the tablets to see if location services are affected in any way

**Comment by mddilley** [comment]
Issue #207 created to improve the Nearby Signals feature

**Comment by mddilley** [comment]
- [ ] Need to field test improvements added in #207 on tablet with Airwatch profile and then this issue can be closed

**Comment by mddilley** [comment]
Improvements tested and work with and w/o Admin mode in the Airwatch configuration. Closing.
