### ISSUE TITLE
Look into sticky footer nav and form buttons with virtual keyboard on Android devices

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-mobile-signals-work-orders#201]
When filling out forms (like the New Work Order form), the sticky nav and form submit footers appear above the virtual keyboard - reducing the amount of space to see/interact with the form. This issue affects Android mobile devices and is not present in iOS.

![Screen Shot 2019-09-23 at 11 53 18 AM](https://user-images.githubusercontent.com/37249039/65446450-019ade80-ddfa-11e9-87f5-dd655f29e54d.png)

**Comment by mateoclarke** [comment]
@mddilley Agree we should seek solutions for this. Let's do some initial research this sprint.
