### ISSUE TITLE
Check in with pilot technicians

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobile-signals-work-orders#224]
See if there is anything else we need to implement before rolling out to everyone. 

~Meeting Scheduled: 10/22~
Meeting Rescheduled: 10/1 
>_Due to not many technicians testing, Billy asked for 5 more technicians to start testing. Sounded like he wanted to get it out ASAP_

**Comment by dianamartin** [comment]
Added 5 more technicians to test per Billy's request
- Melissa Alexander
- Ray Lara
- Frank Guerrero
- Tony Dube
- Austin Hernandez

The past 3 technicians were: 
- Ed Eberle
- Roldan Coronado
- Randy Palos

**Comment by dianamartin** [comment]
@mateoclarke @mddilley @SurbhiBakshi I had created this issue to capture the meeting we had this afternoon. Add your notes here.

**Comment by mateoclarke** [comment]
didn't take any notes but created these issues:
- https://github.com/cityofaustin/atd-mobile-signals-work-orders/issues/228
- https://github.com/cityofaustin/atd-mobile-signals-work-orders/issues/229
- https://github.com/cityofaustin/atd-data-and-performance/issues/336

and we referenced this existing one:
- https://github.com/cityofaustin/atd-mobile-signals-work-orders/issues/226

**Comment by SurbhiBakshi** [comment]
Mobile Signals

Attendees - DM, MC, MD, SB, BB, MA

MA- could input start time and end time, but could not put in received time. When MF clicked on start time, the received time would change back to 12 o clock. Not sure am or pm. 

Happened after first 6 go arounds

BB hasn’t heard back from anyone else

BB thinks M app takes too long to process especially over the weekend, he goes back to Data Tracker. 

DM , MC - Lot of tablet issues, users not used to tablet experience. 

DM - Might need more training.

DM - Need to do a FAQ on tablet usage overall for users to reference. 

DM - need to recruit power users to test the app and then train other users. 

DM recommends killing the app and restarting to get all the functionality back, especially when there is bug like behavior. 

BB- people forget passwords, need some process to manage. 

Tony? Fell down, broke tablet, need to let Scott know.

BB may hire three more, so will need more tablets. 

Taking more pics than the tablet can handle possibly an issue in the future. 

Attaching pics to work orders needs the pic to be taken with the app, can’t be uploaded from device library. 

Work flow/ process may need to be amended/ or accommodated. Esp when it comes to attaching pics. 

Can work orders be stacked and done later? BB discouraged, but sometimes that’s the only way. This can throw off time stamps. Not much can be done, unless records are changed manually?

BB needs to see who the ticket is assigned to immediately on the table, not two buttons in.

DM showed BB Traffic Signal Monitor.
