### ISSUE TITLE
Add ability to upload image from tablet storage to add to work order

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-mobile-signals-work-orders#226]
@mateoclarke @johnclary Is there any reason to avoid adding this feature? I'm thinking it might decrease the use of the in-app camera feature. I'll make a note to bring this up in the feedback meeting on 10/28.

From Toby via email:
>I found something that maybe we can add I took a photo of a of an intersection and it was in my gallery but when I went to add the photo it wanted me to retake the picture is there anyway we can grab it from gallery and/or take a picture of something

**Comment by johnclary** [comment]
Sounds to me like a useful feature to add.
