### ISSUE TITLE
Update to new production URLs for Mobile Signals

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#228]
- [x] update urls to production on devices with Airwatch w/ Danny
- [x] send url update Billy to send to everyone 

https://mobile-signals.mobility.austin.gov

**Comment by dianamartin** [comment]
I emailed Danny the request to update the old web shortcut to the new URL.

**Comment by dianamartin** [comment]
Talked to Danny today, he said he'd do it today and change the admin pin code.

**Comment by dianamartin** [comment]
Sent email to Billy about the new URL
