### ISSUE TITLE
Add Images (uses built-in camera)

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#26]
Maybe using something like this: https://github.com/mabelanger/react-html5-camera-photo

Currently uses upload attachment.

![screen shot 2018-10-02 at 4 40 11 pm](https://user-images.githubusercontent.com/5697474/46378635-e3285a00-c661-11e8-8b0f-8091a7c22d3a.png)

Most often used for insurance purposes.

**Comment by mateoclarke** [comment]
Leaving some notes with resources:
- https://github.com/mabelanger/react-html5-camera-photo
- https://www.knack.com/developer-documentation/#1-uploading-the-file
- https://dev.to/ore/building-an-offline-pwa-camera-app-with-react-and-cloudinary-5b9k

**Comment by sergiogcx** [comment]
We had a lot of success using FilePond:
https://github.com/pqina/filepond

It was great working with it, and customizing it to upload files straight to AWS.

Note that it will need a polyfill to work with IE11:
https://github.com/pqina/filepond-polyfill
