### ISSUE TITLE
Re-Assign Work Order

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#29]
From a Work Order Details page, allow a technician to re-assign the work order including the Lead and Support Technicians

Form: https://builder.knack.com/atd/test-data-tracker#pages/scene_316/views/view_1048

<img width="735" alt="screen shot 2018-10-02 at 4 41 30 pm" src="https://user-images.githubusercontent.com/5697474/46378781-503bef80-c662-11e8-83ad-d5d6ee824ff2.png">

<img width="735" alt="screen shot 2018-10-02 at 4 41 36 pm" src="https://user-images.githubusercontent.com/5697474/46378699-123ecb80-c662-11e8-91f0-80b7d7f6e6db.png">

**Comment by johnclary** [comment]
Based on today's discussion at Sprint Review #4 we confirmed with Billy that functionality is needed and should be allowed so long as the work order is in an **Assigned** or **Unassigned** status.
