### ISSUE TITLE
All Work Orders Page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#37]
On the landing page, we currently have an item "All Issued Jobs". Not that we are focusing on Signals instead of markings, maybe this should be an All Work Orders Page with a search.

The underlying question is what navigations options should a user have on the landing page.

**Comment by dontehightower** [comment]
I went ahead and changed  the "All Issued Jobs" item to "All Work Orders", and set that page up to consume this endpoint --> https://atd.knack.com/test-data-tracker#work-orders3/.

Holding on PR until I have styles that work at less than 580px width, but otherwise working.

**Comment by johnclary** [comment]
Agreed that this should be renamed to "All Work Orders."

I envision this looking identical to the "My Work Orders" view, except it displays all work orders rather than only those connected to the user.
