### ISSUE TITLE
Reproduce the changes we made in the testing environment for the new Work Order Mobile Form page to the production data tracker.

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#66]
https://builder.knack.com/atd/7-feb-2019--test-atd-data-tracker#pages/scene_979

**Comment by johnclary** [comment]
Will require coordination and training with signal techs. Billy mentioned that a Thursday morning would be the best time to train the crews on a new process.

**Comment by mateoclarke** [comment]
@dianamartin, is this a duplicate? I think you knocked this out last week, but maybe we created a newer issue for the work

**Comment by dianamartin** [comment]
@mateoclarke Yes, I think it is. I've done this already.
