### ISSUE TITLE
Search, Filter, and Sort for My Work Orders Page & All Work Orders Page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#77]
A user needs a way to quickly navigate through their assigned work. 

- [x] Search - All Work Orders Page
- [x] Search - My Work Orders Page 
- [x] Filters by status 
- [ ] Sort by modified date, created date, and alphabetical.

**Comment by johnclary** [comment]
The requirements for this should also be applied to https://github.com/cityofaustin/react-knack/issues/37.

**Comment by mateoclarke** [comment]
noted by updating the title.

**Comment by mateoclarke** [comment]
@mddilley knocked out the first step in this with https://github.com/cityofaustin/atd-mobile-signals-work-orders/pull/101

**Comment by mateoclarke** [comment]
Implementing filter on the client side with #151. Not going to worry about sort since it hasn't be articulated as a need for the user. We can reopen that feature later if requested
