### ISSUE TITLE
Asset Details Page

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#82]
This would be a page view that has the history of Work Orders for a given location.

**Comment by mddilley** [comment]
@johnclary @dianamartin I'm starting to work on this issue, and Mateo showed me the view below in the Knack app. What data is most important for this feature? Currently, I'm focusing on creating an autocomplete search field for the assets and mocking out the view. Then, I'll focus on populating Work Orders for the chosen asset and any other data that you both think is important for the users. 

https://atd.knack.com/7-feb-2019--test-atd-data-tracker#work-orders/work-order-details/5c5c8d6bffdb0f62c750f1c5/signal-details/5c5c874effdb0f62c74d25ef/

**Comment by johnclary** [comment]
take a look in the data tracker at the work orders table
on a traffic signal details page. diana can point you to one. we can replicate that as a starting point. we need input from the signals staff to flesh this out. let’s
do that at the rescheduled sprint review.

On Jul 18, 2019, at 17:19, Mike Dilley <notifications@github.com<mailto:notifications@github.com>> wrote:


@johnclary<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjohnclary&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C835523adc1c447b293fa08d70bcdf5fb%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C636990851549388842&sdata=4s3vJ4Olt6rVp5kXMLdvg66aYXkN4unwrMR2D7AXlNQ%3D&reserved=0> @dianamartin<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdianamartin&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C835523adc1c447b293fa08d70bcdf5fb%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C636990851549388842&sdata=EdARMprcGFUAUJNBXw4dVh0SHVt%2FO7x8%2Fshf%2FlDcTiA%3D&reserved=0> I'm starting to work on this issue, and Mateo showed me the view below in the Knack app. What data is most important for this feature? Currently, I'm focusing on creating an autocomplete search field for the assets and mocking out the view. Then, I'll focus on populating Work Orders for the chosen asset and any other data that you both think is important for the users.

https://atd.knack.com/7-feb-2019--test-atd-data-tracker#work-orders/work-order-details/5c5c8d6bffdb0f62c750f1c5/signal-details/5c5c874effdb0f62c74d25ef/<https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fatd.knack.com%2F7-feb-2019--test-atd-data-tracker%23work-orders%2Fwork-order-details%2F5c5c8d6bffdb0f62c750f1c5%2Fsignal-details%2F5c5c874effdb0f62c74d25ef%2F&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C835523adc1c447b293fa08d70bcdf5fb%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C636990851549398840&sdata=3JjPVTORXcgNIMqMhvtKXzhXsGkO7LWoUHE%2FdJlhT2c%3D&reserved=0>

**Comment by mddilley** [comment]
Thanks, John! I'll get this issue to a good structural place and then pick back up on it when we have input from the signals staff.

**Comment by mateoclarke** [comment]
I'll add a placeholder for this discussion to our deck.

**Comment by mateoclarke** [comment]
From the last sprint review:

> Trying to get away from laptops, so need to be able to see on mobile app:
> - Map
> - Details
> - Detectors
> - Work orders
> - Preventative maintenance

Need much of the detail from the top down especially for Preventative Maintenance to use, but for now, let's prioritize these sections above.
