### ISSUE TITLE
Create a separate app instance pointed at the production Knack DB

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#83]
Currently, our app is configured to the Test Data Tracker app ID. We should probably continue having an instance of the app connected to the test knack project but go ahead and deploy a second instance of the code that points the the production data tracker.

**Comment by johnclary** [comment]
This is dependent on us implementing the new single-page work order form in Knack (Data Tracker) production. Will require coordination and training with signal techs. Billy mentioned that a Thursday morning would be the best time to train the crews on a new process.
