### ISSUE TITLE
Implement consistent Button widths

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-mobile-signals-work-orders#84]
@amenity said that @chasechenevert has a sticker sheet with example full width and half width buttons for mobile with good touch target sizes. 

As we consider general styling/themeing improvements, we should: 
- [x] get the sticker sheet
- [ ] review the sticker sheet @chasechenevert button options
- [ ] decide how to implement across the board for this project (as a `<Button/>` component(s)?)

**Comment by amenity** [comment]
[Here is the Janis 2.0 sticker sheet](https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/9dbf77c9-e207-40c6-b9a0-3fde06943327/Buttons/). It includes basic button styles and full-width radio buttons. It doesn't yet include full and half-width buttons, but here are examples of those from the Office of Police Oversight [complaint](https://forms.austintexas.io/police-complain/) and [thanks](https://forms.austin.gov/police-thank/introduction) forms:

- Stacked full-width secondary and primary buttons:
![Screen Shot 2019-03-20 at 2 51 32 PM](https://user-images.githubusercontent.com/1463708/54942563-5ddd7e00-4efd-11e9-8cd4-57ba343b9048.png)

- Half-width buttons:
![Screen Shot 2019-03-25 at 1 00 03 PM](https://user-images.githubusercontent.com/1463708/54943596-a302af80-4eff-11e9-8f33-19eb8011e39f.png)

**Comment by mateoclarke** [comment]
We've updated our buttons to render from a standard `<Button/>` component using bootstrap sizing. Going more in depth with button patterns at this point might be overkill. But worth keeping in mind when/if we standardize our react components with a pattern library via Github's branding/design initiative. cc/ @amenity
