### ISSUE TITLE
Ability to Refresh Page

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-mobile-signals-work-orders#85]
This came up during sprint review yesterday. Users need to occasionally refresh their page in order to see new work orders assignments or record updates from Knack.

The browser refresh button is probably acceptable. Will determine during testing.

**Comment by mateoclarke** [comment]
Doesn't have to be this fancy but this is a common UX pattern we could try...

![image](https://cdn.dribbble.com/users/2726/screenshots/1974767/gearspull.gif)

**Comment by mateoclarke** [comment]
Android browsers do a refresh by default with a swipe down gesture that we actually needed to disable. We discovered this in our usability testing. I think we should rely on the standard browser refresh icon if needed in this use case and leave the app as is.
