### ISSUE TITLE
Documenting and synthesizing results

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-mobile-signals-work-orders#98]

**Comment by mateoclarke** [comment]
This is complete, last thing to do is turn actionable task into github issue which I'll do next.

- [Original Test Plan](https://docs.google.com/document/d/16h8o8zd5kxFX1CbyJJkcAHvfRN0EQuJhlnhduFSb3u0/edit#heading=h.725tzhyfnepr) with notes for summary formats
- [Sheet](https://docs.google.com/spreadsheets/d/1lh7KWk2WZg9t--o-2adhJ6UtX_qD4c3jYrmZukB-Kus/edit#gid=0) for “Affinity Diagramming” listing grouped observations/quotes
- [Slides](https://docs.google.com/presentation/d/1tFZvCeJbKQVoMDdzD2k0-M9amQwR407e4qQYPO6Io5A/edit#slide=id.p) for Sprint Review presenting Results
